/**
 * Pure helpers shared by scripts/release.ts. Kept free of side effects so they
 * can be unit tested with Vitest (scripts/release-lib.test.ts).
 */

import { createHash } from 'node:crypto'
import { createReadStream } from 'node:fs'
import { readdir } from 'node:fs/promises'
import { join } from 'node:path'

/** Artifact extensions published for each release, by platform family. */
export const ARTIFACT_EXTENSIONS = {
  linux: ['.AppImage', '.deb'],
  deb: ['.deb'],
  mac: ['.zip', '.dmg'],
} as const

export type PlatformFamily = keyof typeof ARTIFACT_EXTENSIONS

/**
 * Resolves which artifact families to build. Explicit CLI flags accumulate.
 * An empty flag list defaults to the host OS. `--linux` already includes `.deb`,
 * so passing both keeps only `linux`.
 */
export function resolveReleasePlatforms(flags: PlatformFamily[], hostPlatform: NodeJS.Platform): PlatformFamily[] {
  if (flags.length === 0) {
    return [hostPlatform === 'darwin' ? 'mac' : 'linux']
  }

  const result: PlatformFamily[] = []
  const seen = new Set<PlatformFamily>()
  for (const flag of flags) {
    if (seen.has(flag)) continue
    seen.add(flag)
    result.push(flag)
  }

  if (seen.has('linux') && seen.has('deb')) {
    return result.filter((platform) => platform !== 'deb')
  }

  return result
}

/** Shell command that produces artifacts for one platform family. */
export function buildCommandForPlatform(
  platform: PlatformFamily,
  hostPlatform: NodeJS.Platform,
): { command: string; args: string[] } {
  if (platform === 'mac') {
    return { command: 'pnpm', args: ['-C', 'apps/desktop', 'run', 'build:desktop:mac'] }
  }

  if (hostPlatform !== 'linux') {
    const target = platform === 'deb' ? 'deb' : 'linux'
    return { command: 'bash', args: ['scripts/build-linux-in-container.sh', `--target=${target}`] }
  }

  const script = platform === 'deb' ? 'build:desktop:linux:deb' : 'build:desktop:linux'
  return { command: 'pnpm', args: ['-C', 'apps/desktop', 'run', script] }
}

export interface ReleaseArtifact {
  /** Absolute path to the built artifact on disk. */
  filePath: string
  /** File name (also used as the object key suffix in the bucket). */
  name: string
}

export interface ManifestAsset {
  name: string
  url: string
  sha256: string
  size: number
}

export interface ReleaseManifest {
  format: 'openpos-release-manifest'
  version: string
  notes: string | null
  publishedAt: string
  assets: ManifestAsset[]
}

const ARTIFACT_EXTENSIONS_ALL: string[] = [...ARTIFACT_EXTENSIONS.linux, ...ARTIFACT_EXTENSIONS.mac].map((ext) =>
  ext.toLowerCase(),
)

/**
 * Validates that every package version matches the expected release version.
 * Returns a list of human-readable errors (empty when everything matches).
 */
export function validatePackageVersions(expectedVersion: string, packages: Record<string, string>): string[] {
  return Object.entries(packages)
    .filter(([, version]) => version !== expectedVersion)
    .map(([name, version]) => `${name} version ${version} does not match ${expectedVersion}`)
}

/**
 * Lists release artifacts found in a directory, ignoring non-artifact files,
 * blockmap metadata, and checksum sidecar files generated by electron-builder.
 */
export async function collectArtifacts(distDir: string): Promise<ReleaseArtifact[]> {
  const entries = await readdir(distDir, { withFileTypes: true })

  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => ARTIFACT_EXTENSIONS_ALL.some((ext) => name.toLowerCase().endsWith(ext)))
    .filter((name) => !name.endsWith('.blockmap'))
    .sort()
    .map((name) => ({ filePath: join(distDir, name), name }))
}

/**
 * Checks that every required artifact for the given platforms is present.
 * Returns the missing file descriptions (empty when nothing is missing).
 */
export function findMissingArtifacts(artifacts: ReleaseArtifact[], platforms: PlatformFamily[]): string[] {
  const missing: string[] = []

  for (const platform of platforms) {
    const extensions = ARTIFACT_EXTENSIONS[platform]
    for (const extension of extensions) {
      const normalized = extension.toLowerCase()
      if (!artifacts.some((artifact) => artifact.name.toLowerCase().endsWith(normalized))) {
        missing.push(`a *${extension} artifact for ${platform}`)
      }
    }
  }

  return missing
}

/** Keeps only artifacts required by the selected platform families. */
export function filterArtifactsForPlatforms(
  artifacts: ReleaseArtifact[],
  platforms: PlatformFamily[],
): ReleaseArtifact[] {
  const extensions = new Set(
    platforms.flatMap((platform) => [...ARTIFACT_EXTENSIONS[platform]].map((ext) => ext.toLowerCase())),
  )

  return artifacts.filter((artifact) => [...extensions].some((ext) => artifact.name.toLowerCase().endsWith(ext)))
}

/** Computes the SHA-256 digest of a file, streamed so large artifacts are fine. */
export async function sha256File(filePath: string): Promise<string> {
  const hash = createHash('sha256')
  const stream = createReadStream(filePath)

  for await (const chunk of stream) {
    hash.update(chunk)
  }

  return hash.digest('hex')
}

/** Builds the bucket key for a versioned release asset. */
export function assetKey(prefix: string, version: string, name: string): string {
  const cleanPrefix = prefix.replace(/^\/+|\/+$/g, '')
  return `${cleanPrefix}/v${version}/${name}`
}

/** Builds the bucket key for the update manifest consumed by the desktop app. */
export function manifestKey(prefix: string): string {
  const cleanPrefix = prefix.replace(/^\/+|\/+$/g, '')
  return `${cleanPrefix}/latest.json`
}

/** Builds the public download URL for an asset, given the CDN base URL. */
export function assetUrl(cdnBaseUrl: string, _prefix: string, version: string, name: string): string {
  return `${cdnBaseUrl.replace(/\/+$/, '')}/v/${version}/${name}`
}

/** Builds the public URL of the update manifest consumed by the desktop app. */
export function manifestUrl(cdnBaseUrl: string, prefix: string): string {
  return `${cdnBaseUrl.replace(/\/+$/, '')}/${manifestKey(prefix)}`
}

/** Builds the update manifest served at `latest.json` for the desktop updater. */
export function buildManifest(options: {
  version: string
  notes: string | null
  publishedAt: Date
  cdnBaseUrl: string
  prefix: string
  artifacts: Array<{ name: string; sha256: string; size: number }>
}): ReleaseManifest {
  return {
    format: 'openpos-release-manifest',
    version: options.version,
    notes: options.notes,
    publishedAt: options.publishedAt.toISOString(),
    assets: options.artifacts.map((artifact) => ({
      name: artifact.name,
      url: assetUrl(options.cdnBaseUrl, options.prefix, options.version, artifact.name),
      sha256: artifact.sha256,
      size: artifact.size,
    })),
  }
}
